### ISSUE TITLE
Streaming will raise a ZeroDivisionError

### ISSUE THREAD

**Issue by timreu** [futzu/gumd#2]
Trying to stream a file raises `ZeroDivisionError` in `gums.py`, line 84. The rate is calculated based on elapsed time here. For the first iteration of a dgram, there is no time elapsed (at least on my Laptop). Thus calculating the rate throws the error.

Proposed solution: sleep shortly, after `start_time` is fetched. The function is called only once, so the sleeping will not have a large effect.

**Comment by superkabuki** [comment]
Hey man, I got F2A'ed out of this account and had to make a new  one. 
I've never had that happen to me, I believe you and all, are you using it from pip or just from the repo?

**Comment by superkabuki** [comment]
Hey, I pulled everything over to my new account https://github.com/superkabuki/gums, 
I added the time.sleep() and I'll do a new pip build later today. I also updated new_reader
to make gumc work better, I can get 0 packet loss with the client now over the network.

**Comment by superkabuki** [comment]
```js
Uploading distributions to https://upload.pypi.org/legacy/
Uploading gums-0.0.33-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 kB • 00:00 • 5.9 MB/s
Uploading gums-0.0.33.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 kB • 00:00 • 7.3 MB/s

View at:
https://pypi.org/project/gums/0.0.33/
```
gums 0.0.33 is on pip with your time delay included.

**Comment by timreu** [comment]
Hi! Thanks for building so fast! I used it from pip first. On my computer, scripts from pip are blocked, so I also used it directly from the repo.. I will move to your new repo on superkabuki :)
